controller_list:
 - name: /arobot/left_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
        # left arm
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_elbow_yaw
    - l_elbow_pitch
    - l_wrist_yaw
 - name: /arobot/right_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
        # right arm
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_elbow_yaw
    - r_elbow_pitch
    - r_wrist_yaw