controller_list:
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_elbow_yaw
      - l_elbow_pitch
      - l_wrist_yaw
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_elbow_yaw
      - r_elbow_pitch
      - r_wrist_yaw