i2t_slave_3:
            - 50000
            - 23632
            - 50000
            - 23632
            - 50000
            - 50000
            - 23632
            - 50000
            - 50000

i2t_slave_4:
            - 50000
            - 50000
            - 50000
            - 50000
            - 23632
            - 23632
            - 50000
            - 50000
            - 66000

i2t_slave_5:
            - 3125
            - 3125
            - 50000
            - 66000
            - 50000
            - 3125
            - 23632
            - 23632
            - 23632
