joints_name_slave_3:
            - "r_shoulder_roll"
            - "r_wrist_yaw"
            - "l_hip_roll"
            - "r_hip_yaw"
            - "waist_yaw"
            - "r_shoulder_pitch"
            - "l_hip_yaw"
            - "waist_pitch"
            - "l_shoulder_pitch"


joints_name_slave_4:
            - "r_ankle_pitch"
            - "r_hip_pitch"
            - "l_hip_pitch"
            - "r_hip_roll"
            - "r_elbow_yaw"
            - "r_elbow_pitch"
            - "l_ankle_roll"
            - "l_ankle_pitch"
            - "l_knee_pitch"

joints_name_slave_5:
           - "neck_yaw"
           - "neck_pitch"
           - "l_shoulder_roll"
           - "r_knee_pitch"
           - "r_ankle_roll"
           - "empty"
           - "l_elbow_pitch"
           - "l_wrist_yaw"
           - "l_elbow_yaw"
