arobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  
  

  waist_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: waist_pitch
    pid: {p: 20000.0, i: 0.01, d: 0.0}



  waist_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: waist_yaw
    pid: {p: 10000.0, i: 0.01, d: 0.0}

 # left leg

  l_hip_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_yaw
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  l_hip_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_roll
    pid: {p: 20000.0, i: 0.01, d: 0.0}

  l_hip_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_pitch
    pid: {p: 20000.0, i: 0.01, d: 0.0}

  l_knee_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_knee_pitch
    pid: {p: 20000.0, i: 0.01, d: 0.0}

  l_ankle_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ankle_roll
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  l_ankle_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ankle_pitch
    pid: {p: 10000.0, i: 0.01, d: 0.0}


 # right leg
 
  r_hip_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_yaw
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  r_hip_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_roll
    pid: {p: 20000.0, i: 0.01, d: 0.0}

  r_hip_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_pitch
    pid: {p: 20000.0, i: 0.01, d: 0.0}

  r_knee_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_knee_pitch
    pid: {p: 20000.0, i: 0.01, d: 0.0}

  r_ankle_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ankle_roll
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  r_ankle_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ankle_pitch
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  # left arm

  l_shoulder_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_pitch
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  l_shoulder_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_roll
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  l_elbow_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_elbow_yaw
    pid: {p: 100.0, i: 0.01, d: 0.0}

  l_elbow_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_elbow_pitch
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  l_wrist_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_wrist_yaw
    pid: {p: 10.0, i: 0.01, d: 0.0}


  # right arm

  r_shoulder_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_pitch
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  r_shoulder_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_roll
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  r_elbow_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_elbow_yaw
    pid: {p: 100.0, i: 0.01, d: 0.0}

  r_elbow_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_elbow_pitch
    pid: {p: 10000.0, i: 0.01, d: 0.0}

  r_wrist_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_wrist_yaw
    pid: {p: 10.0, i: 0.01, d: 0.0}

  # head

  neck_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_yaw
    pid: {p: 100.0, i: 0.01, d: 0.0}

  neck_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_pitch
    pid: {p: 100.0, i: 0.01, d: 0.00}
