arobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  

  arobot_trajectory_controller:
    allow_partial_joints_goal: true
    type: effort_controllers/JointTrajectoryController
    joints:
        - waist_pitch
        - waist_yaw
        # left leg
        - l_hip_yaw
        - l_hip_roll
        - l_hip_pitch
        - l_knee_pitch
        - l_ankle_pitch
        - l_ankle_roll
        # right leg
        - r_hip_yaw
        - r_hip_roll
        - r_hip_pitch
        - r_knee_pitch
        - r_ankle_pitch
        - r_ankle_roll
        # left arm
        - l_shoulder_pitch
        - l_shoulder_roll
        - l_elbow_yaw
        - l_elbow_pitch
        - l_wrist_yaw
        # right arm
        - r_shoulder_pitch
        - r_shoulder_roll
        - r_elbow_yaw
        - r_elbow_pitch
        - r_wrist_yaw
        # head
        - neck_yaw
        - neck_pitch
    gains:
        waist_pitch:  {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}
        waist_yaw: {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}
        # left leg
        l_hip_yaw: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_hip_roll: {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}

        l_hip_pitch: {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_knee_pitch: {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_ankle_roll: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_ankle_pitch: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        # right leg
        r_hip_yaw: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_hip_roll: {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_hip_pitch: {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_knee_pitch: {p: 20000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_ankle_roll: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_ankle_pitch: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        # left arm
        l_shoulder_pitch: {p: 8000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_shoulder_roll: {p: 8000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_elbow_yaw: {p: 5000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_elbow_pitch: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        l_wrist_yaw: {p: 10.0, i: 0.01, d: 0.0, i_clamp: 1}
        # right arm
        r_shoulder_pitch: {p: 8000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_shoulder_roll: {p: 8000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_elbow_yaw: {p: 5000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_elbow_pitch: {p: 10000.0, i: 0.01, d: 0.0, i_clamp: 1}
        r_wrist_yaw: {p: 10.0, i: 0.01, d: 0.0, i_clamp: 1}
        # head
        neck_yaw: {p: 100.0, i: 0.001, d: 0.0, i_clamp: 1}
        neck_pitch: {p: 100.0, i: 0.001, d: 0.0, i_clamp: 1}


  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default
