arobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  

  arobot_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - waist_pitch
        - waist_yaw
        # left leg
        - l_hip_yaw
        - l_hip_roll
        - l_hip_pitch
        - l_knee_pitch
        - l_ankle_roll
        - l_ankle_pitch
        # right leg
        - r_hip_yaw
        - r_hip_roll
        - r_hip_pitch
        - r_knee_pitch
        - r_ankle_roll
        - r_ankle_pitch
        # left arm
        - l_shoulder_pitch
        - l_shoulder_roll
        - l_elbow_yaw
        - l_elbow_pitch
        - l_wrist_yaw
        # right arm
        - r_shoulder_pitch
        - r_shoulder_roll
        - r_elbow_yaw
        - r_elbow_pitch
        - r_wrist_yaw
        # head
        - neck_yaw
        - neck_pitch
